### PR TITLE
vgy upload script

### PR DESCRIPTION
**Pull request by ParakramK**
- Added Upload script to post images to vgy
- Added readme for instructions

### CODE REVIEW

**Comment by mmahmoudian** [comment]
@novapix may I ask why this was closed?

**Comment by mmahmoudian** [comment]
@novapix thank you

**Review by mmahmoudian — APPROVED** [review]

**Comment by mmahmoudian** [comment]
Thank you for the contribution. Sorry for the delay in merging.

**Comment by ParakramK** [comment]
> @novapix may I ask why this was closed?

Hey there sorry for the delay 
It was an issue on my side where a script deleted the wrong repo and it was restored via GitHub support

**Pull request merged**
